CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    is_auth INTEGER NOT NULL DEFAULT 0,
    name TEXT NOT NULL DEFAULT "",
    surname TEXT NOT NULL DEFAULT "",
    login TEXT NOT NULL UNIQUE DEFAULT "",
    age INTEGER NOT NULL DEFAULT 0,
    country TEXT NOT NULL DEFAULT "",
    city TEXT NOT NULL DEFAULT "",
    study_place TEXT NOT NULL DEFAULT "",
    password TEXT NOT NULL DEFAULT "",
);

CREATE TABLE IF NOT EXISTS competitions (
    id INTEGER PRIMARY KEY NOT NULL,
    num_of_tasks INTEGER NOT NULL,
    duration INTEGER NOT NULL,
    name TEXT NOT NULL,
    date TEXT NOT NULL,
    is_ended BOOLEAN NOT NULL DEFAULT 0,
    user_id INTEGER NOT NULL
);

